import nodemailer from "nodemailer";

const mailTransporter = nodemailer.createTransport({
  service: "gmail",
  host: "smtp.gmail.com",
  secure: false,
  auth: {
    user: "taqreebat1@gmail.com",
    pass: "nuwhggnhmwlephsy",
  },
});

/**
 * 
 *
  mailTransporter.sendMail({
    from: {
      name: "Taqreebat",
    },
    to: "Zaid.amin28@gmail.com",
    subject: "Account Created",
    html: `
    <center><h2>Wellcome to taqreebat</h2></center>
    <p> This is a testing mail generated by code<p> 
    `,
  });
 */

const mailingController = {
  forgotPasswordMail: (email, urlToRecover) => {
    mailTransporter.sendMail({
      from: {
        name: "Taqreebat",
      },
      to: email,
      subject: "Forgot Password",
      html: `
      <center><h2>Wellcome to taqreebat</h2></center>
      <p>To recover your password please <a href =${urlToRecover}>click here</a> <p>`,
    });
  },
};

export default mailingController;
